---
title: "Summarize Coverage"
output: html_document
---

```{r}
load("res.RData")

library("dscr")
library("ashr")
library(reshape2)
library(ggplot2)
library(dplyr)


neglong = 
  res$negprob %>% 
    select(-user.self,-sys.self,-elapsed,-user.child,-sys.child) %>%
    melt(id.vars=c("method","scenario","seed",".id"),value.name="negprob") %>%
    filter(negprob > 0.9)
 
poslong = 
  res$posprob %>% 
    select(-user.self,-sys.self,-elapsed,-user.child,-sys.child) %>%
    melt(id.vars=c("method","scenario","seed",".id"),value.name="posprob") %>%
    filter(posprob > 0.9)

reslong = 
  res$cdf_score %>% 
    select(-user.self,-sys.self,-elapsed,-user.child,-sys.child) %>%    
    melt(id.vars=c("method","scenario","seed",".id"))

reslong.pos = inner_join(reslong,poslong)
reslong.neg = inner_join(reslong,neglong)

```


Table of lower 5\% tail for all observations
```{r}
xtabs(lt~method+scenario,reslong %>% group_by(scenario,method) %>% summarize(lt = mean(value<0.05))) %>% round(2)
```


Table of lower 5\% tail of positive findings. Because of the unimodal assumption
and the favoritism toward the null this should assess problems
with``over shrinkage" toward 0.
```{r}
xtabs(lt~method+scenario,reslong.pos %>% group_by(scenario,method) %>% summarize(lt = mean(value<0.05))) %>% round(2)
```


Table of lower 5\% tail of negative findings. This should indicate problems with tail behaviour of $g$. The uniform methods tend to over-shrink.
```{r}
xtabs(lt~method+scenario,reslong.neg %>% group_by(scenario,method) %>% summarize(lt = mean(value<0.05))) %>% round(2)
```

```{r}
save_latex_coverage_table=function(df,methodnames,filename,SCENARIONAMES=c("spiky","near-normal","flat-top","skew","big-normal","bimodal")){
  library(xtable)
  df$method=factor(df$method,levels=methodnames)
  df$scenario=factor(df$scenario,levels=SCENARIONAMES)
  mat <- as.matrix(xtabs(lt~method+scenario,df))
  mat <- xtable(mat,digits=rep(2,ncol(mat)+1))
  write(print(mat, 
        sanitize.text.function = function(x){x},
        floating=FALSE, 
        hline.after=NULL, 
        add.to.row=list(pos=list(-1,0, nrow(mat)), 
                        command=c('\\toprule ',
                                  '\\midrule ',
                                  '\\bottomrule '))
      ),file=filename)
  
}
  
save_latex_coverage_table(reslong.neg %>% group_by(scenario,method) %>% summarize(lt = mean(value<0.05)),c("ash.n","ash.u","ash.hu"),"../paper/tables/coverage_neg.tex")
save_latex_coverage_table(reslong.pos %>% group_by(scenario,method) %>% summarize(lt = mean(value<0.05)),c("ash.n","ash.u","ash.hu"),"../paper/tables/coverage_pos.tex")
save_latex_coverage_table(reslong %>% group_by(scenario,method) %>% summarize(lt = mean(value<0.05)),c("ash.n","ash.u","ash.hu"),"../paper/tables/coverage_all.tex")
```

