#look into methods for estimating pi0 conservatively

Do some simulations

```{r}
opts_knit$set(progress = TRUE, verbose = TRUE,root.dir="~/Documents/git/ash/paper/Rcode")
require(ashr)
require(qvalue)
require(fdrtool)
require(mixfdr)
require(locfdr)
require(ggplot2)
#bsd gives standard deviation of beta
#pi0 is simulated to be uniform on [minpi0,1]
basicsim=function(mixsd,mixpi_alt,bsd=1,minpi0=0,seedval = 100,nsamp=1000,niter=50){  
  set.seed(seedval)  
  beta =list()
  betahatsd=list()
  betahat = list()
  zscore = list()
  pval = list()
  betahat.ash.n = list()
  betahat.ash.u = list()
  betahat.ash.npm = list()
  betahat.ash.true = list()
  betahat.qval = list()
  betahat.fdrtool = list()
  betahat.locfdr = list()
  betahat.mixfdr = list()
  pi0 = rep(0,niter)
  for(i in 1:niter){
    pi0[i]=runif(1,minpi0,1)
    mixpi = c(pi0[i],(1-pi0[i])*mixpi_alt)
    sd = sample(mixsd,nsamp,prob=mixpi,replace=TRUE )
    beta[[i]] = rnorm(nsamp,0,sd)
    betahatsd[[i]] = bsd
    betahat[[i]] = beta[[i]]+rnorm(nsamp,0,betahatsd[[i]])
    zscore[[i]] = betahat[[i]]/betahatsd[[i]]
    pval[[i]] = pchisq(zscore[[i]]^2,df=1,lower.tail=F)
    betahat.ash.n[[i]] = ash(betahat[[i]],betahatsd[[i]],pointmass=TRUE,prior="nullbiased",gridmult=2)
    betahat.ash.u[[i]] = ash(betahat[[i]],betahatsd[[i]],pointmass=TRUE,prior="uniform",gridmult=2)
    betahat.ash.npm[[i]] = ash(betahat[[i]],betahatsd[[i]],pointmass=FALSE,prior="uniform",gridmult=2)
    betahat.ash.true[[i]] = ash(betahat[[i]],betahatsd[[i]],g=normalmix(mixpi,rep(0,length(mixpi)),mixsd))
    
    cat("applying q value\n")
    betahat.qval[[i]] = qvalue(pval[[i]])
    cat("applying fdrtool\n")
    betahat.fdrtool[[i]] = fdrtool(pval[[i]],statistic="pvalue",plot=FALSE)
    cat("applying locfdr\n")
    betahat.locfdr[[i]] = try(locfdr(zscore[[i]],nulltype=0,plot=0))
    cat("applying mixfdr\n")
    betahat.mixfdr[[i]] = mixFdr(zscore[[i]],noiseSD=1,theonull=TRUE,plot=FALSE)
  }
  return(list(beta =beta,
  betahatsd=betahatsd,
  betahat = betahat,
  zscore = zscore,
  pval = pval,
  betahat.ash.n = betahat.ash.n,
  betahat.ash.u = betahat.ash.u,
  betahat.ash.npm = betahat.ash.npm,
  betahat.ash.true=betahat.ash.true,
  betahat.qval = betahat.qval,
  betahat.fdrtool = betahat.fdrtool,
  betahat.locfdr = betahat.locfdr,
  betahat.mixfdr = betahat.mixfdr,
    pi0=pi0))
}    
```

```{r, cache=TRUE}
mixsd = c(0,0.25,0.5,1,2)
mixpi_alt = c(0.4,0.2,0.2,0.2) #mixture proportions under the alternative

simres1 = basicsim(mixsd,mixpi_alt,niter=200,nsamp=1000)
simres1a = basicsim(mixsd,mixpi_alt,niter=200,nsamp=10000)
simres2= basicsim(c(0,4),c(1))
simres3=basicsim(c(0,2),c(1),bsd=c(rep(1,500),rep(10,500)))
simres4=basicsim(c(0,2),c(1),bsd=c(rep(1,500),rep(10,500)),minpi0=0.9,seed=200)
```

Show illustrative example
```{r}
altcol="cyan" #colors to use
nullcol="blue" 
nc=40 #number of bins in histograms
ncz = 100 # number of bins in z score histograms
  

plot_FDR_hist=function(sim,iter=1){
  hh.pval = sim$pval[[iter]]
  hh.zscore = sim$zscore[[iter]]
  hh.hist =hist(hh.pval,freq=FALSE,xlab="p value",main="Distribution of p values",nclass=nc,col=altcol)

  hh.q = qvalue(hh.pval)
  abline(h=hh.q$pi0,col=nullcol,lwd=2)
  
  hh.hist$density=rep(hh.q$pi0,length(hh.hist$density))  
  plot(hh.hist,add=TRUE,col=nullcol,freq=FALSE)
  
  abline(v=0.1,lwd=2,col=2)
  
  text(0.05,1.2,labels="A",col=2,cex=1.2)  
  text(0.05,0.4,labels="B",col=2,cex=1.2)  
  text(0.6,3,labels=paste0("FDR = B/(A+B) =  ",round(hh.q$pi0*0.1*length(hh.pval)/sum(hh.pval<0.1),2)),cex=1.2)
}
plot_FDR_hist(simres1,1)
  
```

```{r}
plot_lfdr_hist=function(sim,iter=1){
  require(fdrtool)
  hh.pval=sim$pval[[iter]]
  hh.hist=hist(hh.pval,freq=FALSE,xlab="p value",main="Distribution of p values",nclass=nc,col=altcol)
  
  hh.gren = grenander(ecdf(hh.pval))
  abline(h=min(hh.gren$f.knots),col=nullcol,lwd=2)  
  lines(hh.gren$x.knots,hh.gren$f.knots,lwd=2)
  abline(v=0.1,lwd=2,col=2)
  text(0.1,0.9,labels="a",col=2,cex=1)  
  text(0.1,0.34,labels="b",col=2,cex=1.2)  
  text(0.6,3,labels=paste0("lfdr = b/(a+b) =  ",round(min(hh.gren$f.knots)/approx(hh.gren$x.knots,hh.gren$f.knots,0.1)$y,2)),cex=1.2)
}
plot_lfdr_hist(simres1,1)
```


```{r}
#plot a histogram of z scores, highlighting the alternative distribution
#of z scores that is implied by localfdr values lfdr.
  nullalthist = function(z,lfdr,...){
    h=hist(z, freq=FALSE,col=nullcol,nclass=ncz,...)
    avlfdr = unlist(lapply(split(lfdr,cut(z,h$breaks),drop=FALSE),mean))
    h$density = (1-avlfdr) * h$density
    plot(h,add=TRUE,col=altcol,freq=FALSE)
  }
  
#this one puts the null on the bottom
  altnullhist = function(z,lfdr,...){
    h=hist(z, freq=FALSE,col=altcol,nclass=ncz,...)
    avlfdr = unlist(lapply(split(lfdr,cut(z,h$breaks),drop=FALSE),mean))
    h$density = avlfdr * h$density
    plot(h,add=TRUE,col=nullcol,freq=FALSE)
  }
  
  plotall_hist=function(sim,iter=1,histfun=nullalthist){
    hh.zscore=sim$zscore[[iter]]    
    par(mfcol=c(2,2))
    histfun(hh.zscore,sim$betahat.fdrtool[[iter]]$lfdr,main="fdrtool")  
    histfun(hh.zscore,sim$betahat.locfdr[[iter]]$fdr,main="locfdr")
    histfun(hh.zscore,sim$betahat.mixfdr[[iter]]$fdr,main="mixfdr")
    histfun(hh.zscore,sim$betahat.ash.n[[iter]]$lfdr,main="ash")
    par(mfcol=c(1,1))
  }
  
 # pdf("figures/nullalthist.pdf")
  plotall_hist(simres1,1,nullalthist)
#  dev.off() 

 # pdf("figures/altnullhist.pdf")
  plotall_hist(simres1,1,altnullhist)
#  dev.off()

```


```{r}
#  par(mfcol=c(3,3))
  plot_ecdf=function(sims){
    for(i in 1:length(sims$beta)){
       plot(ecdf(sims$beta[[i]]),xlim=c(-6,6),main=paste0("iteration ",i))
       x = seq(-6,6,length=1000)
       lines(cdf.ash(sims$betahat.ash.n[[i]],x),col=2,lwd=2)
       lines(cdf.ash(sims$betahat.ash.u[[i]],x),col=3,lwd=2)
       lines(cdf.ash(sims$betahat.ash.true[[i]],x),col=4,lwd=2)
    }
  }
  plot_ecdf(simres1)
  plot_ecdf(simres2)
```

```{r}
#Plot pi0 from each method
  get_pi0.fdrtool = function(f){f$param[3]}
  get_pi0.locfdr = function(f){f$fp0[1,3]}
  get_pi0.mixfdr = function(f){f$pi[1]}

  plot_pi0 = function(sims){
    res=list()
    for(i in 1:length(sims)){
      pi0=sims[[i]]$pi0  
      pi0_ash.n=unlist(lapply(sims[[i]]$betahat.ash.n,get_pi0))
      pi0_ash.u=unlist(lapply(sims[[i]]$betahat.ash.u,get_pi0)) 
      pi0_fdrtool = unlist(lapply(sims[[i]]$betahat.fdrtool,get_pi0.fdrtool))
      pi0_locfdr=unlist(lapply(sims[[i]]$betahat.locfdr,get_pi0.locfdr))
      pi0_mixfdr = unlist(lapply(sims[[i]]$betahat.mixfdr,get_pi0.mixfdr))
      pi0_qval = unlist(lapply(sims[[i]]$betahat.qval,"[[","pi0"))
    
      res[[i]] = data.frame(Scenario=i,pi0=pi0,qvalue=pi0_qval,mixfdr=pi0_mixfdr, locfdr=pi0_locfdr, fdrtool=pi0_fdrtool,ash.nullbiased=pi0_ash.n,ash.uniform=pi0_ash.u)
    }
    cbbPalette <- c("#56B4E9", "#009E73", "#F0E442", "#0072B2", "#E69F00", "#000000", "#D55E00", "#CC79A7")
    labels = c('mixfdr','qvalue','locfdr','fdrtool','ash (null-biased)','ash (mle)')
    breaks = c("mixfdr","qvalue","locfdr","fdrtool","ash.nullbiased","ash.uniform")
    
    require(reshape2)
    res.melt = melt(res, id.vars=c("pi0","Scenario"),variable.name="Method")
    res.melt = res.melt[sample(1:nrow(res.melt)),]  
    res.melt$Scenario = as.factor(res.melt$Scenario)
    levels(res.melt$Scenario) = c("Scenario 1a","Scenario 1b","Scenario 2")
    p=ggplot(data=res.melt,aes(pi0,value,colour=Method)) +geom_point(shape=1) +
        facet_grid(. ~ Scenario) +
      geom_abline(colour = "black") +
        xlab("True pi0") +
        ylab("Estimated pi0")
    print(p +scale_y_continuous(limits=c(0,1)) +
          scale_x_continuous(limits=c(0,1)) +
          scale_colour_manual(values=cbbPalette,breaks=breaks,labels=labels) +
          coord_equal(ratio=1))
    
  }

  plot_pi1 = function(sims){
    pi0=sims$pi0  
    pi0_ash.n=unlist(lapply(sims$betahat.ash.n,get_pi0))
    pi0_ash.u=unlist(lapply(sims$betahat.ash.u,get_pi0)) 
    pi0_fdrtool = unlist(lapply(sims$betahat.fdrtool,get_pi0.fdrtool))
    pi0_locfdr=unlist(lapply(sims$betahat.locfdr,get_pi0.locfdr))
    pi0_mixfdr = unlist(lapply(sims$betahat.mixfdr,get_pi0.mixfdr))
    pi0_qval = unlist(lapply(sims$betahat.qval,"[[","pi0"))
    
    res = data.frame(pi0=pi0,qvalue=pi0_qval,mixfdr=pi0_mixfdr, locfdr=pi0_locfdr, fdrtool=pi0_fdrtool,ash.nullbiased=pi0_ash.n,ash.uniform=pi0_ash.u)
    require(reshape2)
    res.melt = melt(res, id.vars=c("pi0"),variable.name="Method")
    p=ggplot(data=res.melt,aes(1-pi0,log2((1-value)/(1-pi0)),colour=Method)) +geom_point(shape=16) +
#        geom_abline(colour = "black") +
        xlab("True pi1") +
        ylab("log2(Estimated pi1/True pi1)")
    print(p +scale_y_continuous(limits=c(-4,4)) +
          scale_x_continuous(limits=c(0,1)))
    
  }

  png("figures/estpi0_sim1sim2.png",height=160,width=540)
    plot_pi0(list(simres1,simres1a,simres2))
  dev.off()
 
```

Figure to show that estimated betahats are not so different
```{r}
  plot(betahat.ash.u[[1]]$PosteriorMean,betahat.ash.n[[1]]$PosteriorMean)
  abline(a=0,b=1,lwd=2,col=2)
  plot(betahat.ash.u[[1]]$PosteriorSD,betahat.ash.n[[1]]$PosteriorSD)
  abline(a=0,b=1,lwd=2,col=2)
```

```{r}
mean_quant=function(x, mult = 1){
      x <- na.omit(x)
      sd <- mult * sqrt(var(x))
      mean <- mean(x)
      data.frame(y = median(x), ymin = quantile(x,0.25) , ymax = quantile(x,0.75))
}

#ptype indicates what type of plot to do
#maxlfsr controls maximum x axis value
#maxy controls maximum y axis value
  plot_lfsr=function(sims,maxlfsr=0.1,ptype=c("lfsr","lfsra","lfdr"),maxy=1){
    ptype=match.arg(ptype)
    xlabtype = ifelse(ptype=="lfdr","lfdr","lfsr")
    res=list()
    for(i in 1:length(sims)){
      lfsr.ash.n= unlist(lapply(sims[[i]]$betahat.ash.n,"[[",ptype))
      lfsr.ash.u= unlist(lapply(sims[[i]]$betahat.ash.u,"[[",ptype))
      if(ptype=="lfdr"){
        lfsr.ash.true= unlist(lapply(sims[[i]]$betahat.ash.true,"[[","lfdr"))
        lfdr.mixfdr = unlist(lapply(sims[[i]]$betahat.mixfdr,"[[","fdr"))
        lfdr.locfdr = unlist(lapply(sims[[i]]$betahat.locfdr,"[[","fdr"))
      } else {
         lfsr.ash.true= unlist(lapply(sims[[i]]$betahat.ash.true,"[[","lfsr"))
      }
        
      subset = lfsr.ash.true<maxlfsr
      
      if(length(subset)>0){  
        res[[i]] = data.frame(Scenario=i,ash.nullbiased=lfsr.ash.n[subset],
                      ash.uniform=lfsr.ash.u[subset],
                      Bayes=0.1*maxlfsr*findInterval(lfsr.ash.true[subset],seq(0,maxlfsr,length=11))-0.05*maxlfsr)
        if(ptype=="lfdr"){
          res[[i]]=data.frame(res[[i]],mixfdr = lfdr.mixfdr[subset])
        }
      }
    }
    
    require(reshape2)
    
    res.melt = melt(res, id.vars=c("Bayes","Scenario"),variable.name="Method")
    

    cbbPalette <- c("#000000","#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
    labels = c('ash (null-biased)','ash (mle)')
    breaks = c("ash.nullbiased","ash.uniform")
    if(ptype=="lfdr"){
      labels = c('mixfdr', labels)
      breaks = c("mixfdr", breaks)
    }
    
    p=ggplot(data=res.melt,aes(Bayes,value,colour=Method)) + 
        facet_grid(. ~ Scenario) +
        #scale_fill_manual(values=cbbPalette) +
        #scale_colour_manual(values=cbbPalette) +
        geom_point(size=1,alpha=0.1) + 
        stat_smooth(se=FALSE,size=2) +
        stat_summary(fun.data="mean_quant", geom="ribbon", alpha=0.25) +
        geom_abline(colour = "black") +
        xlab(paste0(xlabtype," (Bayes)")) +
        ylab(paste0(ptype," (Method)")) 
       
    print(p +scale_y_continuous(limits=c(0,maxy)) +
          scale_x_continuous(limits=c(0,maxlfsr)) +
            scale_colour_manual(values=cbbPalette,breaks=breaks,labels=labels))         
  }

```

```{r}
#plots estimated lfdr and lfsr against truth.
#ptype indicates whether to use lfsr or lfsra
#maxx controls maximum x axis value
#maxy controls maximum y axis value
plot_lfsdr=function(sims,maxx=0.1,ptype=c("lfsr","lfsra"),maxy=1){
    ptype=match.arg(ptype)
    res=list()
    res.lfsr=list()
    res.lfdr=list()
    
    for(i in 1:length(sims)){
      lfsr.ash.true= unlist(lapply(sims[[i]]$betahat.ash.true,"[[","lfsr"))
      lfsr.ash.n= unlist(lapply(sims[[i]]$betahat.ash.n,"[[",ptype))
      lfsr.ash.u= unlist(lapply(sims[[i]]$betahat.ash.u,"[[",ptype))

      lfdr.ash.n= unlist(lapply(sims[[i]]$betahat.ash.n,"[[","lfdr"))
      lfdr.ash.u= unlist(lapply(sims[[i]]$betahat.ash.u,"[[","lfdr"))
      lfdr.ash.true= unlist(lapply(sims[[i]]$betahat.ash.true,"[[","lfdr"))
      lfdr.mixfdr = unlist(lapply(sims[[i]]$betahat.mixfdr,"[[","fdr"))
      lfdr.locfdr = unlist(lapply(sims[[i]]$betahat.locfdr,"[[","fdr"))
    
    
      subset = lfsr.ash.true<maxx
    
      res.lfsr[[i]] = data.frame(Scenario=i,Measure='lfsr', ash.nullbiased=lfsr.ash.n[subset], ash.uniform=lfsr.ash.u[subset],Bayes=0.1*maxx*findInterval(lfsr.ash.true[subset],seq(0,maxx,length=11))-0.05*maxx,mixfdr = NA)
    
      subset = lfdr.ash.true<maxx
      res.lfdr[[i]] = data.frame(Scenario=i,Measure='lfdr', ash.nullbiased=lfdr.ash.n[subset], ash.uniform=lfdr.ash.u[subset],Bayes=0.1*maxx*findInterval(lfdr.ash.true[subset],seq(0,maxx,length=11))-0.05*maxx,mixfdr = lfdr.mixfdr[subset])
    
 
      res[[i]]=rbind(res.lfdr[[i]],res.lfsr[[i]])
    }
    
    require(reshape2)
    
    res.melt = melt(res, id.vars=c("Bayes","Scenario","Measure"),variable.name="Method")
    res.melt$Scenario = as.factor(res.melt$Scenario)
    levels(res.melt$Scenario) = c("Scenario 1a","Scenario 1b","Scenario 2")
    
    cbbPalette <- c("#E69F00","#000000", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
    labels = c('mixfdr','ash (null-biased)','ash (mle)')
    breaks = c("mixfdr","ash.nullbiased","ash.uniform")
    
    p=ggplot(data=res.melt,aes(Bayes,value,colour=Method)) + 
        facet_grid(Measure ~ Scenario ) +
        #scale_fill_manual(values=cbbPalette) +
        #scale_colour_manual(values=cbbPalette) +
        geom_point(size=1,alpha=0.1) + 
        #stat_smooth(se=FALSE,size=2) +
        stat_summary(fun.data="mean_quant", geom="ribbon", alpha=0.25) +
        geom_abline(colour = "red",size=1) +
        xlab("Truth") +
        ylab("Estimate") 
       
    print(p +scale_y_continuous(limits=c(0,maxy)) +
          scale_x_continuous(limits=c(0,maxx)) +
            scale_colour_manual(values=cbbPalette,breaks=breaks,labels=labels))        
  }

```

```{r}
png("figures/lfsdr_sim1sim2_blowup.png",height=427,width=720)
  plot_lfsdr(list(simres1,simres1a,simres2),0.1,ptype="lfsra")
dev.off()
```

```{r}
png("figures/lfsdr_sim1sim2_blowup.png",height=427,width=720)
  plot_lfsdr(list(simres1,simres1a,simres2),0.1,ymax=0.2,ptype="lfsra")
dev.off()
```


```{r}
png("figures/lfdr_sim1sim2_blowup.png",height=160,width=540)
  plot_lfsr(list(simres1,simres1a,simres2),0.1,ptype="lfdr")
dev.off()
```

```{r}
png("figures/lfsra_sim1sim2_blowup.png",height=160,width=540)
  plot_lfsr(list(simres1,simres1a,simres2),0.1,ptype="lfsra")
dev.off()
```

```{r}
png("figures/lfsra_sim1sim2_blowup.png",height=160,width=540)
  plot_lfsr(list(simres1,simres1a,simres2),0.1,ptype="lfsr")
dev.off()
```



```{r}
    plot_pi0(simres3)
  plot_pi1(simres3)
```



QUestion: is the null-biased prior maybe a little too conservative?
Answer: log likelihoods don't suggest they are


```{r}
#hh.ashtrue = hh.ashz
#hh.ashtrue$fitted.g$pi = c(2/3,1/15,1/15,1/15,1/15,1/15)
#hh.ashtrue$fitted.g$mean = c(0,0,0,0,0,0)
#hh.ashtrue$fitted.g$sd = sqrt(c(0,1,0.2,0.4,0.8,3))

#loglik(hh.ashtrue,betahat,sebetahat)
#loglik(hh.ashz,betahat,sebetahat)
```

