```{r}
source("ash.R")
set.seed(100)
#Test VBEM
abf = rbind(c(1,0,0,0),c(0,1,0,0),c(0,0,1,0),c(0,0,1,0),c(0,0,1,0))
eps = 1e-10
abf[abf==0] = eps #replace 0 with small number
print(all.equal(VBEM(abf,c(1,1,1,1))$post,c(2,2,4,1)))
print(all.equal(VBEM(abf,c(1,2,1,1))$post,c(2,3,4,1)))


```




```{r}

source("ash.R")
set.seed(100)


#simulate n beta-hat values, nnull under the null
#with altmean and altsd being the mean and sd of beta under the alternative
simdata=function(n, nnull, altmean, altsd, betasd){
  null = c(rep(1,nnull),rep(0,n-nnull))
  beta = c(rep(0,nnull),rnorm(n-nnull,altmean,altsd))
  betahat = rnorm(n,beta,betasd)
  return(list(null=null,beta=beta,betahat=betahat,betasd=betasd))
}

```

```{r}
ss = simdata(10000,8000,0,2,1)
beta.ash=ash(ss$betahat,ss$betasd)

system.time((post = posterior_dist(beta.ash$fitted.g,ss$betahat,rep(ss$betasd,length(ss$betahat)))))
system.time((PositiveProb = pnormmix(0,post$pi,post$mu,post$sigma,lower.tail=FALSE)))

system.time((PP2 = 1-cdf_post(beta.ash$fitted.g, 0, ss$betahat,rep(ss$betasd,length(ss$betahat)))))    
all.equal(PP2,PositiveProb)
```


```{r}
beta.ash=ash(ss$betahat,ss$betasd,auto=TRUE)
beta.ash.u=ash(ss$betahat,ss$betasd,mixcompdist="uniform",auto=TRUE)
beta.ash.halfu=ash(ss$betahat,ss$betasd,mixcompdist="halfuniform",auto=TRUE)
zscore = ss$betahat/ss$betasd

pval = pchisq(zscore^2,df=1,lower.tail=F)
qval = qvalue(pval)
hist(zscore)
x=seq(min(ss$beta),max(ss$beta),length=1000)
hist(ss$beta,prob=TRUE)
lines(x,density(beta.ash,x),col=2)
lines(x,density(beta.ash.u,x),col=3)
lines(x,density(beta.ash.halfu,x),col=4)
```

```{r}
#Test missing data
ss = simdata(10000,8000,0,2,1)

beta.ash=ash(c(ss$betahat,rep(NA,100)),1)
beta.ash.u=ash(c(ss$betahat,rep(NA,100)),1,mixcompdist="uniform")
beta.ash.halfu=ash(c(ss$betahat,rep(NA,100)),1,mixcompdist="halfuniform")

```

```{r}
system.time((beta.ash=ash(ss$betahat,ss$betasd)))
system.time((beta.ash.auto = ash(ss$betahat, ss$betasd,auto=TRUE)))
system.time((beta.ash.vb.uniform = ash(ss$betahat, ss$betasd,auto=TRUE, VB=TRUE, prior="uniform")))
system.time((beta.ash.vb.null = ash(ss$betahat, ss$betasd,auto=TRUE, VB=TRUE, prior=NULL)))



hist(ss$beta,prob=TRUE,breaks=seq(-7,7,length=20))
x= seq(-4,4,length=10000)
lines(x,density(beta.ash,x),col=2)
lines(x,density(beta.ash.auto,x),col=3)
lines(x,density(beta.ash.vb.uniform,x),col=4)
lines(x,density(beta.ash.vb.null,x),col=5)
beta.ash$fitted.f
beta.ash.auto$fitted.f
beta.ash.vb.uniform$fitted.f

ss = simdata(10000,10000,0,2,1)
system.time((beta.ash=ash(ss$betahat,ss$betasd)))
system.time((beta.ash.auto = ash(ss$betahat, ss$betasd,auto=TRUE)))
system.time((beta.ash.vb.uniform = ash(ss$betahat, ss$betasd,auto=TRUE, VB=TRUE, prior="uniform")))
system.time((beta.ash.vb.null = ash(ss$betahat, ss$betasd,auto=TRUE, VB=TRUE, prior=NULL)))

hist(ss$beta,prob=TRUE,breaks=seq(-7,7,length=20))
x= seq(-4,4,length=10000)
lines(x,density(beta.ash,x),col=2)
lines(x,density(beta.ash.auto,x),col=3)
lines(x,density(beta.ash.vb.uniform,x),col=4)
lines(x,density(beta.ash.vb.null,x),col=5)
summary(beta.ash)
summary(beta.ash.auto)
summary(beta.ash.vb.uniform)
summary(beta.ash.vb.null)
```