TEXCMD := pdflatex 

sims: sim1 simABC

sim1: sim1.R
	R CMD BATCH sim1.R

simABC: simABC.R
	R CMD BATCH simABC.R

figures: fig1 

fig1: makefigs.R  


data: raw.csv
model: model.Rout
paper: plot.Rout paper.pdf

raw.csv: get_data.py
	python get_data.py

clean.csv: clean.sh raw.csv
	source clean.sh

model.Rout: model.R clean.csv
	R CMD BATCH model.R

plot.Rout: plot.R model.Rout
	R CMD BATCH plot.R

main.pdf: main.tex
	$(TEXCMD) $<
	$(TEXCMD) $<
	bibtex *.aux
	$(TEXCMD) $<
